name: ColinITT Tests/Actions
run-name: ${{ github.actor }} is running tests/actions

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: cmake ..
        working-directory: build

      - name: Build with Make
        run: make -j
        working-directory: build

      - name: Make successful
        run: echo "make successful"

      - name: Run minibench w. colintrace
        run: |
          LD_PRELOAD=build/colintrace/libcolintrace.so ./build/minibench/minibench

      - name: Compare trace output (kinda)
        run: |
          TRACE=$(find . -name "trace.pid_*.json" | head -n 1)
          if [ -z "$TRACE" ]; then
            echo "No trace file found!"
            exit 1
          fi
          echo "Comparing $TRACE with sample trace"
          diff -u minibench/compare_trace.json "$TRACE" || echo "Trace differs, but continuing"
          rm -f "$TRACE"

