name: ColinITT Tests/Actions
run-name: ${{ github.actor }} is running tests/actions

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: cmake ..
        working-directory: build

      - name: Build with Make
        run: make -j
        working-directory: build

      - name: Make successful
        run: echo "make successful"
